### PR TITLE
Fixes crashes due to use of the deprecated TaskInternal.execute() method

### PR DESCRIPTION
**Pull request by kunickiaj**
Fixes crashes due to use of the deprecated TaskInternal.execute() method and provides support for multiple sets of includes/excludes.

TaskInternal.execute() is deprecated and also breaks the newer style progress reporting in Gradle. Instead of creating an additional task and using it to add an action to the classes task, this change simply directly adds the execution of the enhance() method.

Not sure if you want to merge this, but this resolved the issue I was having.

### CODE REVIEW

**Comment by radcortez** [comment]
Hi @kunickiaj. Thank you very much for your PR.

Can you let me know some more details? Is this caused by newer versions of Gradle? Let me try it, and I'll be happy to merge your PR.

Cheers,

**Comment by kunickiaj** [comment]
It's related to: https://docs.gradle.org/4.10.2/userguide/custom_tasks.html#sec:reusing_task_logic

It turns out at some point Gradle also rolled out a new default task reporting style in the console output. I've found that calls to TaskInternal.execute() mess up progress reporting (you'll see progress >100% and eventually a crash. The symptom error message is

```Received complete event for an unknown operation id```

One workaround is disabling progress reporting with --console=plain another seems to be not to use TaskInternal.execute(). Since this is going away in Gradle 5.0 made sense to me to understand how one would avoid calling it in the scenario where class files need to be modified.

The recommended solution seems to be to do the class file enhancement in a doLast {} action of the classes task in this case. I can separate this out if you like, since it is a breaking change.

The other change here also changes includes/excludes to a set so that I can specify multiple paths.

**Comment by radcortez** [comment]
Thank you.

I'm on OracleCodeOne this week, so not sure how much time I will have. I would just like to try it and if everything is ok, I'll merge and release a new version.

Cheers,

**Comment by radcortez** [comment]
hey @kunickiaj I've merged your code and made a couple of changes to make sure it will keep the old behaviour.

By any chance, are you able to build and try the code from the develop branch? If you are ok, I'll do a release of this.

Thank you! Cheers.

**Comment by kunickiaj** [comment]
Will give it a try.

**Comment by radcortez** [comment]
Cool! Thanks :)

**Comment by kunickiaj** [comment]
Seems to be working for me.

**Comment by radcortez** [comment]
Great. I'll be doing a release of it then.

**Comment by radcortez** [comment]
Should be done. Here is the new version:
https://bintray.com/radcortez/radcortez/openjpa-gradle-plugin/3.0.0

I've aligned the plugin version with OpenJPA as well.

Thank you for the PR :)

**Pull request closed without merging**
